version: '3'
app: 
  name: wuh
  port: 8080
  env: dev
  domain: localhost
  secretKey: Ys24jvjoKDnfAt77ZR1tV2P11ACv3DUp
mysql: 
  host: 106.14.25.54
  port: 3306
  user: wuh
  password: admin@888
  database: wuh
  charset: utf8mb4
log:
  level: debug
  dir: /tmp/wwwlogs/
redis: 
  host: 106.14.25.54
  port: 6379
  password: admin@888
  db: 0